version: "3.8"
services:
  app:
    build: ./docker/app
    volumes:
      - ./backend:/work

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db-store:
